#!/usr/bin/env python
import os
import sys

import tornado.wsgi
from wsgi.openshift import handlers

if 'OPENSHIFT_REPO_DIR' in os.environ:
    sys.path.append(os.path.join(os.environ['OPENSHIFT_REPO_DIR'], 'wsgi',))
    virtenv = os.environ['OPENSHIFT_PYTHON_DIR'] + '/virtenv/venv'
    os.environ['PYTHON_EGG_CACHE'] = os.path.join(virtenv, 'lib/python3.3/site-packages')
    virtualenv = os.path.join(virtenv, 'bin/activate_this.py')
    try:
        exec(compile(open(virtualenv).read(), virtualenv, 'exec'), dict(__file__=virtualenv))
    except IOError:
        pass


if 'OPENSHIFT_REPO_DIR' in os.environ:
     settings = {
         'cookie_secret': 'TOP_SECRET',
         'static_path' : os.path.join(os.environ['OPENSHIFT_REPO_DIR'], 'wsgi/static'),
         'template_path' : os.path.join(os.environ['OPENSHIFT_REPO_DIR'], 'wsgi/templates'),
         'xsrf_cookies': False,
         'debug': True,
         'login_url': '/login',
     }
else:
     settings = {
         'cookie_secret': 'TOP_SECRET',
         'static_path' : os.path.join(os.getcwd(), 'wsgi/static'),
         'template_path' : os.path.join(os.getcwd(), 'wsgi/templates'),
         'xsrf_cookies': False,
         'debug': True,
         'login_url': '/login',
     }

application = tornado.wsgi.WSGIApplication(handlers, **settings)
